export default {translation: {
  about: 'About',
  add_player: 'Add player',
  add_players: 'Add Players',
  amount: 'Amount',
  best_players: 'Best Players rankings',
  create_new_tournament: 'Create a new tournament',
  create: 'Create',
  choose_champion: 'Choose your champion',
  dashboard: 'Dashboard',
  date: 'Date',
  syncDate: 'Sync date',
  date_from: 'Date from',
  deposit: 'Deposit',
  email: 'Email',
  entry: 'Entry',
  earned: 'earned',
  empty_field: 'Error empty field',
  equal_password: 'Passwords must be equal',
  guade_choose: 'Choose fantasy tournament',
  guade_choose_content: 'Choose fantasy tournament you would like to take part in.',
  guade_create: 'Create your dream team',
  guade_create_content: 'Pick 5 players from the players list.',
  guade_win: 'WIN MONEY',
  guade_win_content: 'Win a tournament and get your money',
  leaderboard: 'Leaderboard',
  log_out: 'Log out',
  login: 'Login',
  login_enter: 'login',
  matches: 'Matches',
  matches_soon: 'Matches will appear soon',
  minimal_entry: 'Minimal entry',
  my_tournaments: 'My tournaments',
  name: 'Name',
  not_yet_tournaments: 'There is no tournaments yet',
  not_satisfied: 'Not satisfied?',
  or: 'or',
  of: 'of',
  operation: 'Operation',
  password: 'Password',
  password_confirm: 'Confirm password',
  place: 'place',
  public_profile: 'Public profile',
  rating: 'Rating',
  register: 'Register',
  register_enter: 'register',
  recent_tournaments: 'Recent tournaments',
  rules: 'Rules',
  scores: 'Scores',
  save_changes: 'Save changes',
  start: 'Start',
  setting_profile: 'Setting profile',
  team: 'Team',
  transactions: 'Transactions',
  tournaments: 'Tournaments',
  tournaments_name: 'Tournaments name',
  tournament_list: 'Tournament(from list)',
  transactions_history: 'Transactions History',
  update_data: 'Your data has been updated.',
  username: 'Username',
  users: 'Users',
  user_not_participated: 'This user has not yet participated in tournaments',
  withdraw: 'Withdraw',
  winner_get: 'Winner will get:',
  waiting_players: 'Waiting for new players',
  zero_tournaments: 'This user has not yet participated in tournaments',
  select_tournament: 'Select tournament',
  tournament: 'Tournament',
  there_is_no_tournaments_yet: 'There is no tournaments yet',
  tournament_over: 'Tournament is over! Winner is {{winner}}',
  he_got_prize: 'He got {{prize}} prize',
  match: 'Match',
  join_tournament: 'Join Tournament',
  join_tournament_and: 'Join Tournament and choose your champions',
  wait_matches: 'Waiting for match results',
  free: 'Free',
  position: 'Position',
  points: 'Points',
  is_going_on: 'Is going on',
  archive: 'Archive',
  will_be_soon: 'Will be soon',
  champion_avatar: 'Champion Avatar',
  choose_your_champion: 'Choose your champion',
  created_by: 'Created By',
  information: 'Information',
  prize_pool: 'Prize Pool',
  entry_cost: 'Entry Cost',
  original_tournament: 'Original Tournament',
  my_team: 'My Team',
  youve_been_registered_for_the_tournament: 'you been registered for the tournament',
  free_tournament: 'Do you want to start with such a team?',
  balance: 'Balance',
  admin: 'Admin',
}};