export default {translation: {
  about: 'Обо мне',
  add_player: 'Добавить игрока',
  add_players: 'Добавить игроков',
  amount: 'Сумма',
  best_players: 'Рейтинг лучших игроков',
  create_new_tournament: 'Создать турнир',
  create: 'Создать',
  choose_champion: 'Выбери 5 чемпионов',
  date: 'Дата',
  date_from: 'Дата от',
  syncDate: 'Дата синхронизации',
  dashboard: 'Панель управления',
  deposit: 'Депозит',
  email: 'Электронная почта',
  entry: 'Цена',
  earned: 'зачислено',
  empty_field: 'Ошибка пустое поле',
  equal_password: 'Пароли должны совпадать',
  guade_choose: 'Выбери фэнтези турнир',
  guade_choose_content: 'Выберите фэнтези турнир, в котором вы хотели бы принять участие.',
  guade_create: 'Создайте команду своей мечты',
  guade_create_content: 'Выберите 5 лучших из списка игроков.',
  guade_win: 'ВЫИГРАТЬ ДЕНЬГИ',
  guade_win_content: 'Выиграй турнир и получи деньги',
  leaderboard: 'Таблица лидеров',
  log_out: 'Выйти',
  login: 'Вход',
  login_enter: 'войти',
  matches: 'Матчи',
  matches_soon: 'Матчи скоро появятся',
  minimal_entry: 'Минимальная цена',
  my_tournaments: 'Мои турниры',
  name: 'Имя',
  not_yet_tournaments: 'Турниров еще нет',
  not_satisfied: 'Не устраивает?',
  or: 'или',
  of: 'из',
  operation: 'Операция',
  password: 'Пароль',
  password_confirm: 'Подтвердить пароль',
  place: 'место',
  public_profile: 'Публичный профиль',
  rating: 'Рейтинг',
  register: 'Завербоваться',
  register_enter: 'завербоваться',
  recent_tournaments: 'Недавние турниры',
  rules: 'Правила',
  scores: 'Результаты',
  save_changes: 'Сохранить изменения',
  start_with: 'Вход через',
  setting_profile: 'Настройки профиля',
  team: 'Команда',
  transactions: 'Операции',
  tournaments: 'Турниры',
  tournaments_name: 'Название турнира',
  tournament_list: 'Турнир(из списка)',
  transactions_history: 'История операций',
  update_data: 'Ваши данные обновлены.',
  username: 'Логин',
  users: 'Пользователи',
  user_not_participated: 'Этот пользователь еще не участвовал в турнирах',
  withdraw: 'Снять',
  winner_get: 'Победитель получит:',
  waiting_players: 'Ожидаем новых игроков',
  zero_tournaments: 'Этот пользователь еще не участвовал в турнирах',
  select_tournament: 'Выберите турнир',
  tournament: 'Турнир',
  there_is_no_tournaments_yet: 'Еще нет турниров',
  tournament_over: 'Турнир завершён! Победитель - {{winner}}.',
  he_got_prize: 'Он получил {{prize}} приз.',
  match: 'Матч',
  join_tournament: 'Присоединиться к турниру',
  join_tournament_and: 'Присоединяйся к турниру и выбирай своих чемпионов',
  wait_matches: 'Ожидаем результатов матчей',
  free: 'Free',
  settings_locale: 'Выбранный язык',
  settings_locale_ru: 'Русский',
  settings_locale_en: 'Английский',
  position: 'Позиция',
  points: 'Поинты',
  is_going_on: 'Is going on',
  is_over: 'Турнир завершён',
  archive: 'Архив',
  will_be_soon: 'Скоро будет',
  champion_avatar: 'Champion Avatar',
  choose_your_champion: 'Выбери своего чемпиона',
  created_by: 'Cоздатель',
  information: 'Информация',
  prize_pool: 'Призовой фонд',
  entry_cost: 'Стоимость входа',
  original_tournament: 'Реальный турнир',
  my_team: 'Моя команда',
  youve_been_registered_for_the_tournament: 'Вы были зарегистрированы для участия в турнире',
  free_tournament: 'Вы хотите с таким составом стартовать?',
  balance: 'Баланс',
  admin: 'Админ',
  please_name_tournament: 'Пожалуйста, напишите название турнира',
  please_date_tournament: 'Пожалуйста, выберите дату турнира',
  please_players_tournament: 'Пожалуйста, выберите игроков турнира',
  tournament_created: 'Турнир создан',
  tournament_updated: 'Турнир был успешно обновлен!',
  tournament_deleted: 'Турнир был удален',
  player_from_list: 'Пожалуйста, выберите игрока из списка',
  player_alreadt: 'Этот игрок уже принимает участие в турнире',
  no_any_matches: "Матчей нет",
  create_tournament: 'Создать турнир',
  delete_tournament: 'Удалить турнир',
  update_tournament: 'Обновить турнир',
  want_delete_tournament: 'Вы действительно хотите удалить турнир?',
  tournament_name: 'Название турнира',
  tournament_date: 'Дата турнира',
  tournament_players: 'Игроки турнира',
  select_player: 'Выбрать игрока',
  add: 'Добавить',
  tournament_matches: 'Турнирные матчи',
  create_match: 'Создать матч',
  menu: 'Меню',
  fantasy_tournaments: 'Фэнтези Турниры',
  tournament_rules: 'Правила турнира',
  champions: 'Чемпионы',
  user_updated: 'Пользователь был успешно обновлен!',
  yes: 'Да',
  no: 'Нет',
  update_user: 'Обновить пользователя',
  champion_updated: 'Чемпион был успешно обновлен!',
  please_champion_name: 'Пожалуйста, напишите имя чемпиона',
  champion_created: 'Чемпион был успешно создан!',
  champion_deleted: 'Чемпион был успешно удалён!',
  add_new_champion: 'Добавить нового чемпиона',
  add_champion: 'Добавить чемпиона',
  editing: 'Редактирование',
  delete_champion: 'Удалить чемпиона',
  update_champion: 'Обновить чемпиона',
  no_champion: "Чемпионов нет",
  want_remove_champion: 'Вы действительно хотите удалить чемпиона?',
  champion_name: 'Имя чемпиона',
  champion_photo: 'Аватар чемпиона',
  was_deleted: 'был удалён',
  tournament_not_finalized: 'Турнир не завершен',
  finalize_tournament: 'Завершить турнир',
  entry_sum: 'Сумма входа',
  winner: 'Победитель',
  rule_updated: 'Правило было успешно обновлено!',
  please_rule_name: 'Пожалуйста, напишите название правила',
  rule_created: 'Правило было успешно создано!',
  rule_deleted: 'Правило было успешно удалено!',
  add_new_rule: 'Добавить новое правило',
  create_rule: 'Создать правило',
  delete_tule: 'Удалить правило',
  update_rule: 'Обновить правило',
  add_rule: 'Добавить правило',
  no_rules: "Нет правил",
  want_remove_rule: 'Вы действительно хотите удалить правило?',
  rule_name: 'Название правила',
  finalize_all: 'Завершить все турниры',
  newbie: 'новичок',
  transactions_history: 'История операций',
  really_want_create: 'Вы действительно хотите создать турнир?',
  kills: 'Убийства',
  assists: 'Помощи',
  deaths: 'Смерти',
}};