export default {translation: {
  about: 'Обо мне',
  best_players: 'Рейтинг лучших игроков',
  create_new_tournament: 'Создать турнир',
  create: 'Создать',
  date_from: 'Дата от',
  deposit: 'Депозит',
  earned: 'заработано',
  email: 'Электронная почта',
  entry: 'Цена',
  guade_choose: 'Выбери фэнтези турнир',
  guade_choose_content: 'Выберите фэнтези турнир, в котором вы хотели бы принять участие.',
  guade_create: 'Создайте команду своей мечты',
  guade_create_content: 'Выберите 5 лучших из списка игроков.',
  guade_win: 'ВЫИГРАТЬ ДЕНЬГИ',
  guade_win_content: 'Выиграй турнир и получи деньги',
  log_out: 'Выйти',
  login: 'Вход',
  login_enter: 'войти',
  minimal_entry: 'Минимальная цена',
  my_tournaments: 'Мои турниры',
  name: 'Имя',
  not_satisfied: 'Not satisfied',
  or: 'или',
  password: 'Пароль',
  password_confirm: 'Подтвердить пароль',
  place: 'место',
  public_profile: 'Публичный профиль',
  rating: 'Рейтинг',
  register: 'Завербоваться',
  register_enter: 'завербоваться',
  recent_tournaments: 'Недавние турниры',
  rules: 'Правила',
  scores: 'Очки',
  save_changes: 'Сохранить изменения',
  start: 'Вход',
  setting_profile: 'Настройки профиля',
  transactions: 'Операции',
  tournaments: 'Турниры',
  tournaments_name: 'Название турнира',
  tournament_list: 'Турнир(из списка)',
  username: 'Логин',
  users: 'Пользователей',
  user_not_participated: 'Этот пользователь еще не участвовал в турнирах',
  withdraw: 'Снять'
}};